services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    command: ./start.sh
    volumes:
      - static_content:/home/app/backend/staticfiles
      - media_content:/home/app/backend/media
    env_file:
      - ./backend/.env.prod
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/db/.env.prod.db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    volumes:
      - dist:/frontend/dist/

  nginx:
    image: nginx:1.25-alpine
    container_name: nginx
    depends_on:
      - backend
    restart: always
    volumes:
      - ./nginx/prod/prod.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
      - static_content:/usr/src/app/static:ro
      - media_content:/usr/src/app/media:ro
      - dist:/frontend/dist/
    ports:
      - "80:80"
      - "443:443"

volumes:
  postgres_data:
  static_content:
  media_content:
  dist:

