services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: org_tree_backend
    restart: always
    command: >
      /bin/sh -c "python3 manage.py migrate --no-input && python3 manage.py collectstatic --no-input && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - static_content:/home/app/backend/staticfiles
      - media_content:/home/app/backend/media
    env_file:
      - ./backend/.env.prod
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: org_tree_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/db/.env.prod.db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: org_tree_frontend
    volumes:
      - dist:/frontend/dist/

  nginx:
    image: nginx:1.25-alpine
    container_name: org_tree_nginx
    depends_on:
      - backend
    restart: always
    volumes:
      - ./nginx/prod/prod.conf:/etc/nginx/conf.d/default.conf:ro
      - static_content:/usr/src/app/static:ro
      - media_content:/usr/src/app/media:ro
      - dist:/frontend/dist/
      # - ./nginx/prod/fullchain.pem:/etc/nginx/ssl/live/orgtree.vinsit.ru/fullchain.pem
      # - ./nginx/prod/privkey.pem:/etc/nginx/ssl/live/orgtree.vinsit.ru/privkey.pem
    ports:
      - "80:80"
      - "443:443"

volumes:
  postgres_data:
  static_content:
  media_content:
  dist:

