services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    command: ./start.sh
    volumes:
      - static_content:/home/app/backend/staticfiles
      - media_content:/home/app/backend/media
    env_file:
      - ./backend/.env.prod
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/db/.env.prod.db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    ports:
      - "5173:5173"

volumes:
  postgres_data:
  static_content:
  media_content:

