services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: org_tree_backend
    restart: always
    command: >
      /bin/sh -c "python3 manage.py migrate --no-input && python3 manage.py collectstatic --no-input && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - static_content:/home/app/backend/staticfiles
      - media_content:/home/app/backend/media
    env_file:
      - ./backend/.env.prod
    ports:
      - "8100:8000"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: org_tree_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/db/.env.prod.db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: org_tree_frontend
    volumes:
      - dist:/frontend/dist/

volumes:
  postgres_data:
  static_content:
  media_content:
  dist:

